### ISSUE TITLE
null is not an object (evaluating 'RNPFManager.requestAuthorization')

### ISSUE THREAD

**Issue by majid-achy** [vforvasile/react-native-photos-framework#3]
Hello,
I am trying to use this library but when importing it and trying to use it I am getting this error: null is not an object (evaluating 'RNPFManager.requestAuthorization')
This is for an android app built with react native
I installed the library using: npm install rn-photos-framework

the code in which i am using it is:

import React, {useEffect} from 'react';
import {View, Text} from 'react-native';
import RNPhotosFramework from 'rn-photos-framework';
export default function AlbumsScreen() {
  
  useEffect(() => {
        RNPhotosFramework.requestAuthorization()
  }, []);
  return (
    //<View>
     // <Text>Albums Screen</Text>
   // </View>
  );
}

the dependencies i am using are:

  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.7",
    "react-native-screens": "^2.9.0",
    "react-native-vector-icons": "^7.0.0",
    "rn-photos-framework": "^1.0.7"
  },

tried uninstalling it then reinstalling but didn't work
tried linking it but also didn't work 
please help me with this issue

thank you for your time

**Comment by vforvasile** [comment]
Hey!

This library is dedicated for `iOS` only.

On Android try [react-native-cameraroll](https://github.com/react-native-community/react-native-cameraroll)
